Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    # Ensure we're running the latest Ubuntu 16
    config.vm.provision 'shell', inline: 'sudo apt-get update && sudo apt-get dist-upgrade -y'

    config.vm.define :controller do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'
        ubuntu.vm.hostname = 'controller'

        # Management
        ubuntu.vm.network :private_network, ip: '10.40.40.40', netmask: '255.255.255.0'

        # Give the box 8G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 8192
            v.cpus = 4
        end
    end

    config.vm.define :compute_1 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'
        ubuntu.vm.hostname = 'compute-1'

        # Management
        ubuntu.vm.network :private_network, ip: '10.40.40.41', netmask: '255.255.255.0'

        # Public
        ubuntu.vm.network :public_network, ip: '192.168.40.1', netmask: '255.255.255.0'

        # Give the box 2G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 2048
        end
    end

    config.vm.define :compute_2 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'
        ubuntu.vm.hostname = 'compute-2'

        # Management
        ubuntu.vm.network :private_network, ip: '10.40.40.42', netmask: '255.255.255.0'

        # Public
        ubuntu.vm.network :public_network, ip: '192.168.50.1', netmask: '255.255.255.0'

        # Give the box 2G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 2048
        end
    end
end
