Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    # Inject hosts file
    config.vm.provision 'file', source: 'files/hosts', destination: '~/hosts'
    config.vm.provision 'shell', inline: 'sudo cp /home/ubuntu/hosts /etc/hosts'

    # Ensure we're running the latest Ubuntu 16
    config.vm.provision 'shell', inline: 'sudo apt-get update && sudo apt-get dist-upgrade -y'

    config.vm.define :controller do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'
        ubuntu.vm.hostname = 'controller'

        # Public
        ubuntu.vm.network :private_network, ip: '10.40.40.40'
        # Management
        ubuntu.vm.network :private_network, ip: '192.168.40.40'

        # Give the box 4G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 4096
        end
    end

    config.vm.define :compute_1 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'
        ubuntu.vm.hostname = 'compute-1'

        # Public
        ubuntu.vm.network :private_network, ip: '10.40.41.40'
        # Management
        ubuntu.vm.network :private_network, ip: '192.168.41.40'

        # Give the box 1G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 1024
        end
    end

    config.vm.define :compute_2 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/xenial64'

        # Public
        ubuntu.vm.network :private_network, ip: '10.40.42.40'
        # Management
        ubuntu.vm.network :private_network, ip: '192.168.42.40'

        # Give the box 2G memory
        config.vm.provider 'virtualbox' do |v|
            v.memory = 2048
        end
    end
end
